"""Figure: per-edge distribution of the embedding-model ablation -- generic
(all-MiniLM-L6-v2) vs domain-specific (PubMedBERT) semantic confidence,
across the same 224 original-dataset PubMed-cited edges.

Domain-specific side uses the real stored per-edge `confidence` values
(exact, n=224). Generic side replicates kg/pubmed_linker.py's original
_compute_confidence() methodology exactly: full abstract text fetched live
via NCBI efetch, truncated to 512 characters, encoded with all-MiniLM-L6-v2.
Edges whose PMID still returns no abstract (5/197 unique PMIDs -- some due
to the confirmed PubmedBookArticle parsing gap in _fetch_abstracts_batch())
get a 0.5 fallback, matching kg/pubmed_linker.py's own fallback behavior.

Result: generic mean 0.4944, min -0.0221. (An earlier version of this
figure used the pre-stored 300-char abstract_snippet instead of the full
abstract text and landed at a noticeably different mean -- a real
methodology error, since corrected here.)

Source data: data/processed/embedding_ablation_224_edges.json (generated by
live-refetching each edge's PubMed abstract and re-encoding with both
embedding models; see the module docstring above for exact methodology).

Run from the project root: python -m scripts.render_embedding_ablation_distribution
"""
import json
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams["font.family"] = "Times New Roman"
matplotlib.rcParams["font.size"] = 10

DATA_PATH = "data/processed/embedding_ablation_224_edges.json"
FIGDIR = "figures"

with open(DATA_PATH) as f:
    full = json.load(f)

generic = full["generic"]
domain_specific = full["domain_specific"]

fig, ax = plt.subplots(figsize=(7, 4.8))
bins = [i / 40 for i in range(-4, 41)]
ax.hist(generic, bins=bins, alpha=0.6, color="#E69F00", edgecolor="black", linewidth=0.4, hatch="///",
        label=f"all-MiniLM-L6-v2 (generic)  mean={sum(generic)/len(generic):.3f}")
ax.hist(domain_specific, bins=bins, alpha=0.6, color="#0072B2", edgecolor="black", linewidth=0.4,
        label=f"PubMedBERT (domain-specific)  mean={sum(domain_specific)/len(domain_specific):.3f}")
ax.axvline(0, color="black", linewidth=0.8)
ax.set_xlabel("Semantic confidence score (cosine similarity)")
ax.set_ylabel("Number of edges")
ax.set_title(f"Embedding Model Ablation, Per-Edge Score Distribution\n(n={len(generic)} original-dataset PubMed-cited edges)")
ax.legend(fontsize=8)
plt.tight_layout()
plt.savefig(f"{FIGDIR}/embedding_ablation_distribution.png", dpi=300)
plt.close()
print("Saved embedding_ablation_distribution.png")
